name: Java 21 CI

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Build with Gradle
        run: ./gradlew assemble
      - name: Style check
        run: ./gradlew checkstyleMain
      - name: Test with Java 21
        run: ./gradlew test -PtestOnJava=21 --stacktrace
