name: Java 11 CI macOS (Apple)

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 11
      - name: Build with Gradle
        run: ./gradlew assemble
      - name: Test with Gradle
        run: ./gradlew test
